image = "/capstor/scratch/cscs/ljiayong/enroot_images/qlib_eiger.sqsh"
mounts = ["/capstor/scratch/cscs/ljiayong:/capstor/scratch/cscs/ljiayong",
          "/iopsstor/scratch/cscs/ljiayong:/iopsstor/scratch/cscs/ljiayong",
          "/users/ljiayong/projects/qlib:/users/ljiayong/projects/qlib",
          ]
workdir = "/users/ljiayong/projects/qlib"
writable = true
